title: Project
pages: false
files: true
fields:
  title:
    label: Titulo (interno)
    type:  text

  projectTitle:
    label: Titulo
    type:  text
    width: 1/2

  projectImage:
    label: Imagen
    type:  image
    required: True
    width: 1/2

  projectText:
    label: Texto
    type:  textarea

  projectQuoteBool:
    label: Quote
    type:  checkbox
    text:  Mostrar
    width: 1/3

  projectQuoteImg:
    label: Foto
    type:  image
    width: 1/3

  projectQuoteText:
    label: Texto
    type:  text
    width: 1/3
